# Jekyll
markdown: redcarpet

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title
relative_permalinks: true

# Setup
title:               Brace Yourself
url:                 http://padjenation.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tim Padjen
  url:               https://twitter.com/tpadjen
  email:             tpadjen@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/tpadjen/padjenation

header_pages:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'