# Jekyll
markdown: redcarpet

# Permalinks
#
permalink:           /:title

# Setup
title:               Brace Yourself
url:                 http://padjenation.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Tim Padjen
  url:               https://github.com/tpadjen
  email:             tpadjen@gmail.com
  twitter:           https://twitter.com/tpadjen
  github:            https:github.com/tpadjen

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/tpadjen/tpadjen.github.io

include: ['_pages']

header_pages:
  About: '/about/'

feed: '/atom.xml'